openapi: 3.0.0
info:
  title: Chat Application API
  version: 2.0.0
  description: Real-time chat application with file sharing - Supabase powered

servers:
  - url: https://wjxogegvcssxhlurtzqo.supabase.co/rest/v1
    description: Supabase REST API

paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: number
                    example: 1640000000000

components:
  schemas:
    Message:
      type: object
      required:
        - id
        - username
        - content
        - timestamp
      properties:
        id:
          type: string
          format: uuid
          description: Unique message identifier
        username:
          type: string
          minLength: 1
          maxLength: 20
          description: Sender's username
        content:
          type: string
          maxLength: 500
          description: Message content
        timestamp:
          type: number
          description: Unix timestamp in milliseconds
        file_url:
          type: string
          format: uri
          description: URL of attached file (optional)
        file_name:
          type: string
          description: Original filename (optional)
        file_size:
          type: integer
          minimum: 0
          maximum: 10485760
          description: File size in bytes, max 10MB (optional)
        file_type:
          type: string
          description: MIME type of the file (optional)

    User:
      type: object
      required:
        - id
        - username
        - joinedAt
      properties:
        id:
          type: string
          description: Socket connection ID
        username:
          type: string
          minLength: 1
          maxLength: 20
          description: User's display name
        joinedAt:
          type: number
          description: Unix timestamp when user joined

    JoinRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 1
          maxLength: 20
          description: Desired username
        password:
          type: string
          description: Fixed password for authentication

    SendMessageRequest:
      type: object
      properties:
        content:
          type: string
          maxLength: 500
          description: Message content (optional if file is attached)
        file_url:
          type: string
          format: uri
          description: URL of uploaded file (optional)
        file_name:
          type: string
          description: Original filename (optional)
        file_size:
          type: integer
          minimum: 0
          maximum: 10485760
          description: File size in bytes (optional)
        file_type:
          type: string
          description: MIME type of the file (optional)

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
